https://www.ncei.noaa.gov/access/metadata/landing-page/bin/iso?id=gov.noaa.ncdc:C00516

In [1]:
import pandas as pd

df = pd.read_csv("https://www.ncei.noaa.gov/data/global-summary-of-the-day/access/2023/72364099999.csv")

# https://www.ncei.noaa.gov/data/global-summary-of-the-day/access/2023/

In [2]:
print(f"Number of instances: {len(df)}")
print(f"Number of features : {len(df.columns)}")

Number of instances: 365
Number of features : 28

In [3]:
column_names_list = df.columns.tolist()
print(column_names_list)

['STATION', 'DATE', 'LATITUDE', 'LONGITUDE', 'ELEVATION', 'NAME', 'TEMP', 'TEMP_ATTRIBUTES', 'DEWP', 'DEWP_ATTRIBUTES', 'SLP', 'SLP_ATTRIBUTES', 'STP', 'STP_ATTRIBUTES', 'VISIB', 'VISIB_ATTRIBUTES', 'WDSP', 'WDSP_ATTRIBUTES', 'MXSPD', 'GUST', 'MAX', 'MAX_ATTRIBUTES', 'MIN', 'MIN_ATTRIBUTES', 'PRCP', 'PRCP_ATTRIBUTES', 'SNDP', 'FRSHTT']

In [4]:
df.tail(5)

,STATION,DATE,LATITUDE,LONGITUDE,ELEVATION,NAME,TEMP,TEMP_ATTRIBUTES,DEWP,DEWP_ATTRIBUTES,...,MXSPD,GUST,MAX,MAX_ATTRIBUTES,MIN,MIN_ATTRIBUTES,PRCP,PRCP_ATTRIBUTES,SNDP,FRSHTT
360,72364099999,2023-12-27,31.880444,-106.70325,1253.58,DONA ANA CO INTERNATIONAL JETPORT ARPT SANTA T...,39.6,24,10.4,24,...,8.9,999.9,53.6,*,28.4,*,0.0,I,999.9,0
361,72364099999,2023-12-28,31.880444,-106.70325,1253.58,DONA ANA CO INTERNATIONAL JETPORT ARPT SANTA T...,41.5,24,11.1,24,...,7.0,999.9,55.4,*,26.6,*,0.0,I,999.9,0
362,72364099999,2023-12-29,31.880444,-106.70325,1253.58,DONA ANA CO INTERNATIONAL JETPORT ARPT SANTA T...,40.7,24,14.5,24,...,7.0,999.9,57.2,*,26.6,*,0.0,I,999.9,0
363,72364099999,2023-12-30,31.880444,-106.70325,1253.58,DONA ANA CO INTERNATIONAL JETPORT ARPT SANTA T...,39.7,24,14.6,24,...,5.1,999.9,55.4,*,26.6,*,0.0,I,999.9,0
364,72364099999,2023-12-31,31.880444,-106.70325,1253.58,DONA ANA CO INTERNATIONAL JETPORT ARPT SANTA T...,43.0,24,12.4,24,...,15.0,20.0,60.8,*,24.8,*,0.0,I,999.9,0

In [5]:
import os

base_dir = '../data/raw'
weather_data_dir = os.path.join(base_dir, 'weather_data')
file_name = 'weather_raw.parquet'
os.makedirs(weather_data_dir, exist_ok=True)
file_path = os.path.join(weather_data_dir, file_name)

df.to_parquet(file_path, compression='gzip')